### ISSUE TITLE
Medical Diagnosis page simply wrong.

### ISSUE THREAD

**Issue by Diamond-Frost** [GenderDysphoria/GenderDysphoria.fyi#112]
I am upset that there's been such a lack of research into this topic here. 

Your page states that apart from the DSM5, no other standardized mental health medical catalogue exists. This is plainly wrong as there is another: The International Statistical Classification of Diseases and Related Health Problems, published by the WHO, also known as the ICD. Currently we use the 10th and 11th revision. Every other country *except* the US use this standard for mental health issues along side all other medical issues or some expansion of it - Including China (CCD - Expansion of ICD-10), Russia (Standard), Saudi Arabia (Australian Modification) and even North Korea (Soviet ICD-7)! 

The US has their own version of the ICD, abbreviated as ICD-10-CM (Clinical Modification; of course the USA had to make it seem like they are the world.), which they do not use for mental health, instead they use the DSM5 which itself makes it much harder to get a lot of diagnosis, especially because it does not catalogue symptoms, only disorders and is extremely human-hostile (Autism Levels, Requiring severe depression for Dysphoria, etc). The ICD does not have these issues.

The definition you have written of Gender Dysphoria according to DSM5 is also wrong. There's a reason why its so hard to get an actual diagnosis, it requires you to be severely depressed as a result of your transgender nature. Mind you, the ICD-10/ICD-11 (The revision made no change to that code) does not require that. The definition you gave more closely resembles the ICD in fact. 

Please, when you already try and do good - which I feel like you are - also do an extensive research into what you write before publishing it, I already knew of the ICD beforehand, but with a single google search and 2 clicks, I was able to disprove the entire first paragraph of the mentioned page. I have found some other minor issues in your pages that do much less harm, but should still be extensively researched and adjusted accordingly.

**Comment by Twipped** [comment]
> Your page states that apart from the DSM5, no other standardized mental health medical catalogue exists

I believe this is the sentence you are referring to? (emphasis added for relevance)

> This section is going to focus on **the diagnostic criteria** under the American Psychiatric Association’s Diagnostic and Statistical Manual of Mental Disorders, version five (DSM-5). The reason I’m focusing on this standard is because, well, nobody else has one.

Could you please point to me [where in ICD-11](https://icd.who.int/browse11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f90875286) it describes how to diagnose gender dysphoria? As far as I have read, the ICD purely describes various conditions and assigns categorical codes to them for standardization across the medical industry. It is neither a diagnostic tool, nor even an index of symptoms.

I feel it is worth noting that during the 2021 tribunal of Dr Helen Webberley, a major point made by the defense for why Dr Webberley relied non-UK diagnostic criteria (specifically DSM5) and treatment guidelines (UCSF transgender treatment protocols) was that there were no other available resources for her at the time, and everyone she consulted with recommended those two resources as being the best available options.

> it requires you to be severely depressed as a result of your transgender nature

That was a requirement in DSM4, [it is not a requirement in DSM5)(https://cdn.website-editor.net/30f11123991548a0af708722d458e476/files/uploaded/DSM%2520V.pdf). From page 451:

> Gender dysphoria refers to the distress that may accompany the incongruence between one's experienced or expressed gender and one's assigned gender. Although not all indi­viduals will experience distress as a result of such incongruence, many are distressed if the desired physical interventions by means of hormones and/or surgery are not available. The current term is more descriptive than the previous DSM-IV term gender identity disor­der and focuses on dysphoria as the clinical problem, not identity per se.

![image](https://user-images.githubusercontent.com/231157/200938486-04609e16-9385-4ad3-92a9-fe99d6d5bb68.png)
![image](https://user-images.githubusercontent.com/231157/200938509-c17ab473-fdf5-4de6-a886-eb449ca8ca3c.png)
![image](https://user-images.githubusercontent.com/231157/200938779-2050d76d-41a4-454f-b9be-0f28147f8594.png)
![image](https://user-images.githubusercontent.com/231157/200939202-0a7f7508-6c28-4b74-ae64-7ec77a41ba44.png)

Now you could have made a point that as of this year we have WPATH SoC8, which *does* finally define a global standard for diagnosis ([pages 31-42 for adults, 43-66 for adolescents](https://www.tandfonline.com/doi/full/10.1080/26895269.2022.2100644)), and then I could have replied that, yes, I haven't been able to update the book yet for the release of SoC 8. At the time of writing, all we had was SoC 7, which explicitly did NOT define diagnostic criteria, choose to defer that to regional bodies.

But you didn't. 

> Please, when you already try and do good - which I feel like you are - also do an extensive research into what you write before publishing it

Please, when you try to do good, take into consideration that someone who wrote 34k words on the subject of gender dysphoria because it is their five year autistic special interest would most certainly have read both versions of the DSM, both versions of the SoC, and both versions of the ICD, as well as many numerous other resources that you've likely never even heard of.
