### ISSUE TITLE
In the surgical transition section of the treatment chapter, under "Other trans Feminine Surgeries", brazilian but lift should at leat say "Proceed with caution"

### ISSUE THREAD

**Issue by linusrg1** [GenderDysphoria/GenderDysphoria.fyi#149]
A period I had in my life of enjoying watching plastic surgery videos taught me that Brazilian Butt Lifts can be quite risky as there are various important things in that area. This New Your Times article as well as this Cleveland Clinic page explain things better than I could. 

The Cleveland Clinic page:
https://my.clevelandclinic.org/health/treatments/23308-brazilian-butt-lift

The New York Times article:
https://www.nytimes.com/2021/08/19/style/brazillian-butt-lift-bbl-how-much-risks.html

**Comment by Twipped** [comment]
From [Brazilian Butt Lift–Associated Mortality: The South Florida Experience](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9896146/) on PubMed.

> In early May 2019, ASERF repeated the gluteal fat grafting online survey by sending 5048 invitations; 572 responses (11.3%) were received from plastic surgeons reporting on 29,843 cases. This second survey demonstrated that the societies’ education campaigns had been remarkably successful in that 94% of respondents noted that they were aware of the new safety recommendations and 86% of respondents were now only fat grafting in the subcutaneous plane. This survey asked respondents if they were aware of any new BBL deaths, and estimated that by 2019, the BBL mortality rate had dropped to **1/14,921**, which if accurate, would have surpassed the safety profile of abdominoplasty (1/13,193 at the time of the survey).

For reference the odds of being hit by a motor vehicle while out for a walk is 3.2 in 10,000. The mortality rate for simply living as a trans person is higher than 1/200.

BBL is perfectly safe when conducted by properly trained and accredited surgeons. The reason the procedure gets such a bad rap is because of areas where there are no regulations on how the procedure is performed or who is allowed to perform it. Just as with getting any other "elective" surgical procedure, one should do their due diligence when picking the doctor and don't shop based on price.
