### ISSUE TITLE
Gender Abolition

### ISSUE THREAD

**Issue by anoyeddicktater** [GenderDysphoria/GenderDysphoria.fyi#48]
I am a 17 year old who is currently questioning my gender. I also am a gender abolitionist, but I do believe that gender dysphoria is a thing as I experience it (according to your gender dysphoria fyi). I think that gender roles and gendered stereotypes are extremely harmful. The only way to get rid of these things is to remove gender (gender roles will always exist with gender). While some may think that gender abolition will hurt trans people, trans people will only be helped by the removal of gender as they will be able to present however they want without social stigmatization. People who are questioning their gender will also be able to dress as the gender they might want to be and decide if that's the life they want to live. There is also an innumerable amount of harm done by gender and gender roles that don't directly affect trans people.

**Comment by Twipped** [comment]
Is there something actionable in this post, or are you just stating your viewpoint on gender abolition?

I do intend to rework the section on GA, because there's a lot more theory and philosophy besides the suppressive and erasing aspects of the ideology, but the subject is both deep in nuance and broad in its reach. It's not something that can be quickly summarized.
