### ISSUE TITLE
Stop referring to intersex variations as "DSDs" or "disordered".

### ISSUE THREAD

**Issue by SadieCat** [GenderDysphoria/GenderDysphoria.fyi#75]
Ref: https://genderdysphoria.fyi/en/chromosomes

This language is generally considered offensive by many [intersex-led support organisations](https://interactadvocates.org/interact-statement-on-intersex-terminology/) and intersex people (including myself).

You should ideally refer to intersex people and variations as "intersex" in all scenarios but if you *really* need to refer to intersex variations in this way then you should use ***differences** in sex development* as used by many health organisations e.g. [the NHS](https://www.nhs.uk/conditions/differences-in-sex-development/)).

The article also erroneously says that not all people with "DSDs" are intersex which is also incorrect and should be removed.

**Comment by Twipped** [comment]
The project is open source, anyone is free to suggest edits. If the wording on the page is inappropriate, please submit a pull request with different wording. The wording is based upon the language used on wikipedia for these conditions, which is *also* publicly editable. It also explicitly says that it is *the medical community* that refers to them as such. A paragraph explaining that the intersex community uses different language would be extremely welcome.

I am not intersex, I do not have the facility to speak as an authority on intersex social matters. That's why there's a big damn disclaimer at the top of the page asking for people to contribute their own narratives. It's also why I stuck to describing these things from a purely medical science perspective.

The purpose of that page is to drill into the binary-centric position that transphobes take of saying there is only XX and XY and nothing else. The entire crux of the argument is that not even chromosomal sex is binary, and here is why. If you can maintain that position while making the page more accommodating and equally informing, then **PLEASE CONTRIBUTE**.
